#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Calculator.Resource", IsApplication=true)]

namespace Calculator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int alignmentMode = 2130771972;
			
			// aapt resource value: 0x7f010002
			public const int columnCount = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int columnOrderPreserved = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int layout_column = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int layout_columnSpan = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int layout_columnWeight = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int layout_gravity = 2130771981;
			
			// aapt resource value: 0x7f010007
			public const int layout_row = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int layout_rowSpan = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int layout_rowWeight = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int orientation = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int rowCount = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int rowOrderPreserved = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int useDefaultMargins = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int colorAccent = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int colorPrimary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int colorPrimaryDark = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040001
			public const int activity_horizontal_margin = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int activity_vertical_margin = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int default_gap = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int fab_margin = 2130968579;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int calc_Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int alignBounds = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int alignMargins = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int bottom = 2131230724;
			
			// aapt resource value: 0x7f08001d
			public const int btn0 = 2131230749;
			
			// aapt resource value: 0x7f080019
			public const int btn1 = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int btn2 = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int btn3 = 2131230747;
			
			// aapt resource value: 0x7f080016
			public const int btn4 = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int btn5 = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int btn6 = 2131230744;
			
			// aapt resource value: 0x7f080013
			public const int btn7 = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int btn8 = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int btn9 = 2131230741;
			
			// aapt resource value: 0x7f080020
			public const int btnAdd = 2131230752;
			
			// aapt resource value: 0x7f08001f
			public const int btnDelete = 2131230751;
			
			// aapt resource value: 0x7f080023
			public const int btnDiv = 2131230755;
			
			// aapt resource value: 0x7f08001c
			public const int btnDot = 2131230748;
			
			// aapt resource value: 0x7f08001e
			public const int btnEqual = 2131230750;
			
			// aapt resource value: 0x7f080021
			public const int btnMinus = 2131230753;
			
			// aapt resource value: 0x7f080022
			public const int btnMult = 2131230754;
			
			// aapt resource value: 0x7f080024
			public const int calculator_text_view = 2131230756;
			
			// aapt resource value: 0x7f080005
			public const int center = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int center_horizontal = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int center_vertical = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int clip_horizontal = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int clip_vertical = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int end = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int fill = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int fill_horizontal = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int fill_vertical = 2131230733;
			
			// aapt resource value: 0x7f080000
			public const int horizontal = 2131230720;
			
			// aapt resource value: 0x7f08000e
			public const int left = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int right = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int start = 2131230736;
			
			// aapt resource value: 0x7f080012
			public const int textView = 2131230738;
			
			// aapt resource value: 0x7f080011
			public const int top = 2131230737;
			
			// aapt resource value: 0x7f080001
			public const int vertical = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActivityCalculator = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int layout2 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int button_calculator = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] GridLayout = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 4
			public const int GridLayout_alignmentMode = 4;
			
			// aapt resource value: 2
			public const int GridLayout_columnCount = 2;
			
			// aapt resource value: 6
			public const int GridLayout_columnOrderPreserved = 6;
			
			// aapt resource value: 0
			public const int GridLayout_orientation = 0;
			
			// aapt resource value: 1
			public const int GridLayout_rowCount = 1;
			
			// aapt resource value: 5
			public const int GridLayout_rowOrderPreserved = 5;
			
			// aapt resource value: 3
			public const int GridLayout_useDefaultMargins = 3;
			
			public static int[] GridLayout_Layout = new int[] {
					16842996,
					16842997,
					16842998,
					16842999,
					16843000,
					16843001,
					16843002,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 1
			public const int GridLayout_Layout_android_layout_height = 1;
			
			// aapt resource value: 2
			public const int GridLayout_Layout_android_layout_margin = 2;
			
			// aapt resource value: 6
			public const int GridLayout_Layout_android_layout_marginBottom = 6;
			
			// aapt resource value: 3
			public const int GridLayout_Layout_android_layout_marginLeft = 3;
			
			// aapt resource value: 5
			public const int GridLayout_Layout_android_layout_marginRight = 5;
			
			// aapt resource value: 4
			public const int GridLayout_Layout_android_layout_marginTop = 4;
			
			// aapt resource value: 0
			public const int GridLayout_Layout_android_layout_width = 0;
			
			// aapt resource value: 10
			public const int GridLayout_Layout_layout_column = 10;
			
			// aapt resource value: 11
			public const int GridLayout_Layout_layout_columnSpan = 11;
			
			// aapt resource value: 12
			public const int GridLayout_Layout_layout_columnWeight = 12;
			
			// aapt resource value: 13
			public const int GridLayout_Layout_layout_gravity = 13;
			
			// aapt resource value: 7
			public const int GridLayout_Layout_layout_row = 7;
			
			// aapt resource value: 8
			public const int GridLayout_Layout_layout_rowSpan = 8;
			
			// aapt resource value: 9
			public const int GridLayout_Layout_layout_rowWeight = 9;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
